### ISSUE TITLE
Incorrect interpretation of :DIRECTORY string in MAKE-PATHNAME

### ISSUE THREAD

**Issue by chaitanyagupta** [Clozure/ccl#101]
[MAKE-PATHNAME](http://www.lispworks.com/documentation/HyperSpec/Body/f_mk_pn.htm) states that:

> If the directory is a string, it should be the name of a top level directory, and should not contain any punctuation characters; that is, specifying a string, str, is equivalent to specifying the list (:absolute str). 

So, `(pathname-directory (make-pathname :directory "tmp"))` should return `(:ABSOLUTE "tmp")`. However CCL returns `(:RELATIVE "tmp")`.

Lisp details:

```lisp
? (lisp-implementation-version)
"Version 1.11-r16635  (DarwinX8632)"

? *features*
(:PRIMARY-CLASSES :COMMON-LISP :OPENMCL :CCL :CCL-1.2 :CCL-1.3 :CCL-1.4 :CCL-1.5 :CCL-1.6 :CCL-1.7 :CCL-1.8 :CCL-1.9 :CCL-1.10 :CCL-1.11 :CLOZURE :CLOZURE-COMMON-LISP :ANSI-CL :UNIX :OPENMCL-UNICODE-STRINGS :IPV6 :OPENMCL-NATIVE-THREADS :OPENMCL-PARTIAL-MOP :MCL-COMMON-MOP-SUBSET :OPENMCL-MOP-2 :OPENMCL-PRIVATE-HASH-TABLES :X8632-TARGET :X8632-HOST :X86 :X86-TARGET :X86-HOST :DARWIN-HOST :DARWIN-TARGET :DARWINX86-TARGET :DARWINX8632-TARGET :DARWINX8632-HOST :32-BIT-TARGET :32-BIT-HOST :DARWIN :LITTLE-ENDIAN-TARGET :LITTLE-ENDIAN-HOST)
```

**Comment by xrme** [comment]
Yes, that's a bug, and it's fixed in the development branch and in the 1.11.5 release.

see 64ef3f63f44bf400ce15ca329d1b17201022c3f9 and https://trac.clozure.com/ccl/ticket/1203

You can get the current release from https://github.com/Clozure/ccl/releases/tag/v1.11.5

**Comment by chaitanyagupta** [comment]
Thanks! It seems the homebrew version is a bit older, I had assumed it would have the latest release.

**Comment by Shinmera** [comment]
This bug still persists in 1.11.5 in the following form:
```
(pathname-directory (make-pathname :directory "")) ; => NIL
```
rather than the expected `(:absolute)` or `(:absolute "")`.
