### ISSUE TITLE
CCL not picking up local systems under ~/common-lisp

### ISSUE THREAD

**Issue by mdbergmann** [Clozure/ccl#331]
This is more of an inquiry.
Apparently the version of asdf that is part of CCL should be recent enough.
But for some reason CCL doesn't pick up the projects I have under `~/common-lisp`.

According to the asdf docs this should work:
https://www.common-lisp.net/project/asdf/asdf.html#Configuring-ASDF-to-find-your-systems

The same works with ECL and SBCL. All have the same quicklisp configuration in rc files.

Am I missing something?

**Comment by svspire** [comment]
I don't know why it's not working but if you put something like the following in your ~/ccl-init.lisp file it should fix it.

`(asdf:initialize-source-registry '(:source-registry
  (:TREE #P"~/common-lisp/") :IGNORE-INHERITED-CONFIGURATION))
`

**Comment by mdbergmann** [comment]
ok, thanks. I'll give that a try.

**Comment by mdbergmann** [comment]
Not sure. Doesn't seem to work.
I have that directly after the quicklisp setup in .ccl-init.lisp
Projects still not found.

**Comment by mdbergmann** [comment]
I don't quite understand this.
This folder seems to be part of the default configuration of ASDF.
Is CCL modifying this?

If someone can point me in a direction in the sources of CCL I will have a look.

**Comment by svspire** [comment]
Are you using Catalina and if so have you given CCL full disk access?

**Comment by mdbergmann** [comment]
I've tried that. But it doesn't make a difference when ccl is started through Terminal.app which has full disk access.
And SBCL and ECL would have the same issue. Neither of those has explicit 

How can I find out which folders ASDF it looks in?
It's probably not *central-registry*, or?

```
? asdf:*central-registry*
(#P"/Users/mbergmann/quicklisp/quicklisp/")
```

**Comment by rprimus** [comment]
Thu Jun 25 18:05:24 BST 2020

Inspecting the exported symbols for the `asdf` package:
```
? ASDF/SOURCE-REGISTRY:*DEFAULT-SOURCE-REGISTRIES*
(ASDF/SOURCE-REGISTRY:ENVIRONMENT-SOURCE-REGISTRY
 ASDF/SOURCE-REGISTRY:USER-SOURCE-REGISTRY
 ASDF/SOURCE-REGISTRY:USER-SOURCE-REGISTRY-DIRECTORY
 ASDF/SOURCE-REGISTRY:DEFAULT-USER-SOURCE-REGISTRY
 ASDF/SOURCE-REGISTRY:SYSTEM-SOURCE-REGISTRY
 ASDF/SOURCE-REGISTRY:SYSTEM-SOURCE-REGISTRY-DIRECTORY
 ASDF/SOURCE-REGISTRY:DEFAULT-SYSTEM-SOURCE-REGISTRY)
```
```
? (ASDF/SOURCE-REGISTRY:USER-SOURCE-REGISTRY-DIRECTORY)
#P"/Users/rprimus/dotfiles/.config/common-lisp/source-registry.conf.d/"
```
```
? asdf:*central-registry*
(#P"/Users/rprimus/dotfiles/quicklisp/quicklisp/")
```

@mdbergmann : what does `(asdf/source-registry:user-source-registry-directory)` return for you?

**Comment by mdbergmann** [comment]
Ah, I didn't get that those are functions (methods?).

```
? (asdf/source-registry:user-source-registry-directory)
NIL
```

**Comment by rprimus** [comment]
Thu Jun 25 18:56:16 BST 2020

What about:
```
(asdf/source-registry:default-user-source-registry)
```

P.S.  I edited the previous a few times.  Please re-read.

**Comment by mdbergmann** [comment]
Yep, have the latest:

`(:QUICKLISP :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 ...`

Something is quite odd.

Something of the below helps:

```
? (asdf:initialize-source-registry '(:source-registry (:TREE (:HOME "common-lisp/")) :INHERIT-CONFIGURATION))
? (asdf/source-registry:user-source-registry-directory)
NIL
? (asdf:initialize-source-registry '(:source-registry (:TREE (:HOME "common-lisp/")) :IGNORE-INHERITED-CONFIGURATION))
? (asdf/source-registry:user-source-registry-directory)
NIL
? (asdf/source-registry:system-source-registry-directory)
NIL
```

It seems that no local directories are setup.
I'm using a stock CCL-1.12 installed via Homebrew.
My .ccl-init.lisp is quite blank, except the quicklisp definition.

The best practices assume that a folder '~/common-lisp' exists and asdf will load local projects from it.

Is it possible to try a custom asdf install instead of the one shipped with CCL?

**Comment by rprimus** [comment]
Thu Jun 25 19:52:39 BST 2020

function `asdf:initialize-source-registry` sets `asdf:*source-registry-parameter*`.  To verify, in a fresh CCL repl:
1. check `asdf:*source-registry-parameter*`
2. evaluate one of the above `initialize-source-registry` expressions
3. redo step 1.

Just a few more debugging steps:
1. start a new CCL repl
2. evaluate `(asdf/source-registry:default-user-source-registry)`  and provide the results
3. in the terminal, run `tree ~/common-lisp/`  and provide the results
4. for one of your systems in `~/common-lisp`, in the CCL repl, load the system via `asdf:load-system` and provide the results.

**Comment by mdbergmann** [comment]
OK. I think we got it.

First the results. The ASDF config appears to be fine.

```
? (asdf/source-registry:default-user-source-registry)
(:SOURCE-REGISTRY (:TREE (:HOME "common-lisp/")) (:DIRECTORY #P"/Users/mbergmann/.local/share/common-lisp/systems/") (:TREE #P"/Users/mbergmann/.local/share/common-lisp/source/") :INHERIT-CONFIGURATION)
```

The folders in `common-lisp`:

```
❯ l .
total 0
drwxr-xr-x    5 mbergmann  staff   160B 25 Jun 21:12 .
drwxr-xr-x@ 168 mbergmann  staff   5,3K 25 Jun 21:12 ..
lrwxr-xr-x    1 mbergmann  staff    49B 12 Jun 09:34 cl-gserver -> /Users/mbergmann/Development/MySources/cl-gserver
lrwxr-xr-x    1 mbergmann  staff    53B 12 Jun 09:34 cl-swbymabeweb -> /Users/mbergmann/Development/MySources/cl-swbymabeweb
drwxr-xr-x   19 mbergmann  staff   608B 25 Jun 14:35 cl-swbymabeweb2
```

As soon as I fully copy the source folder in there it works:

```
? (asdf:find-system "cl-swbymabeweb")
#<SYSTEM "cl-swbymabeweb">
```

So it appears symlinks are not supported.

The question now is where are they not supported?

**Comment by rprimus** [comment]
Thu Jun 25 20:36:19 BST 2020

Symlinks are followed for `clasp`, `ecl` and `sbcl`.

https://gitlab.common-lisp.net/asdf/asdf/-/blob/master/source-registry.lisp#L200

**Comment by mdbergmann** [comment]
Not for CCL. Great stuff. Why not?

**Comment by rprimus** [comment]
Thu Jun 25 20:56:47 BST 2020

>  Why not?

No idea.  Might be worth asking the `ASDF` maintainers. (`resolve-symlinks* was added in commit 072692f1bb2e043a97d6cee9fd98c16260538772, however specilisation for `ecl` and `sbcl` already existed for `lisp-implementation-directory`.)

**Comment by svspire** [comment]
Symlinks are supported in ASDF. Whether they are treated differently in CCL I don't know. I recommend you search the ASDF manual for "link farm." There's some discussion therein.

**Comment by svspire** [comment]
I dug into this a bit more. ASDF's source code contains comments like the following:
```
"Return a list of the entries in a directory by calling DIRECTORY.
Try to override the defaults to not resolving symlinks, if implementation allows."

  "DIRECTORY-FILES tries NOT to resolve symlinks if the implementation permits this,
but the behavior in presence of symlinks is not portable. Use IOlib to handle such situations."

"The behavior in presence of symlinks is not portable. Use IOlib to handle such situations."

    "Given a DIRECTORY pathname designator, return a list of the subdirectories under it.
The behavior in presence of symlinks is not portable. Use IOlib to handle such situations."
```
And indeed at least with CCL, if you have _symlinks to directories_ in ~/common-lisp/, ASDF doesn't find them. I had never tried this before but I just tested it and it indeed does not work. However, if you put _symlinks to asd files_ in ~/common-lisp/, ASDF will find your systems. I just tested that and it works. Note that I did not have to call the `asdf:initialize-source-registry` form above to get this to work.

So I guess the moral is that in ASDF, symlinks to _files_ work, but symlinks to _directories_ are not guaranteed to be portable. I wish the ASDF manual would describe this behavior; their description of "link farms" doesn't distinguish between the two types of symlinks.

**Comment by mdbergmann** [comment]
OK, thanks for looking into this.
I think that symlinks to .asd files is good enough.
Symlinks to directories would be better though.

Should this be mentioned somewhere?

Otherwise for me this is resolved.

**Comment by svspire** [comment]
You might want to file an issue at https://gitlab.common-lisp.net/asdf/asdf/-/issues or email Robert Goldman with a pointer to this page. I think it's more a documentation issue than a functionality issue.
